name: foxid
version: 1.3.0
description: A library for manipulating with FOxID - unique identifiers with the possibility of lexicographic sorting.
repository: https://codeberg.org/lutracorp/foxid
issue_tracker: https://codeberg.org/lutracorp/foxid/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  base32: ^2.1.3
  collection: ^1.19.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
